# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: decryptor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='decryptor.proto',
  package='examples.decryptor_server',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x64\x65\x63ryptor.proto\x12\x19\x65xamples.decryptor_server\"A\n\x14GetDecryptionRequest\x12\x12\n\nciphertext\x18\x01 \x02(\x0c\x12\x15\n\x0ckey_filename\x18\x91N \x02(\x0c\"*\n\x15GetDecryptionResponse\x12\x11\n\tplaintext\x18\x01 \x02(\t2{\n\tDecryptor\x12n\n\x07\x44\x65\x63rypt\x12/.examples.decryptor_server.GetDecryptionRequest\x1a\x30.examples.decryptor_server.GetDecryptionResponse\"\x00'
)




_GETDECRYPTIONREQUEST = _descriptor.Descriptor(
  name='GetDecryptionRequest',
  full_name='examples.decryptor_server.GetDecryptionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ciphertext', full_name='examples.decryptor_server.GetDecryptionRequest.ciphertext', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_filename', full_name='examples.decryptor_server.GetDecryptionRequest.key_filename', index=1,
      number=10001, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=111,
)


_GETDECRYPTIONRESPONSE = _descriptor.Descriptor(
  name='GetDecryptionResponse',
  full_name='examples.decryptor_server.GetDecryptionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='plaintext', full_name='examples.decryptor_server.GetDecryptionResponse.plaintext', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=155,
)

DESCRIPTOR.message_types_by_name['GetDecryptionRequest'] = _GETDECRYPTIONREQUEST
DESCRIPTOR.message_types_by_name['GetDecryptionResponse'] = _GETDECRYPTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetDecryptionRequest = _reflection.GeneratedProtocolMessageType('GetDecryptionRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETDECRYPTIONREQUEST,
  '__module__' : 'decryptor_pb2'
  # @@protoc_insertion_point(class_scope:examples.decryptor_server.GetDecryptionRequest)
  })
_sym_db.RegisterMessage(GetDecryptionRequest)

GetDecryptionResponse = _reflection.GeneratedProtocolMessageType('GetDecryptionResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETDECRYPTIONRESPONSE,
  '__module__' : 'decryptor_pb2'
  # @@protoc_insertion_point(class_scope:examples.decryptor_server.GetDecryptionResponse)
  })
_sym_db.RegisterMessage(GetDecryptionResponse)



_DECRYPTOR = _descriptor.ServiceDescriptor(
  name='Decryptor',
  full_name='examples.decryptor_server.Decryptor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=157,
  serialized_end=280,
  methods=[
  _descriptor.MethodDescriptor(
    name='Decrypt',
    full_name='examples.decryptor_server.Decryptor.Decrypt',
    index=0,
    containing_service=None,
    input_type=_GETDECRYPTIONREQUEST,
    output_type=_GETDECRYPTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DECRYPTOR)

DESCRIPTOR.services_by_name['Decryptor'] = _DECRYPTOR

# @@protoc_insertion_point(module_scope)
